### ISSUE TITLE
Send clan tag

### ISSUE THREAD

**Issue by micheljung** [FAForever/faf-java-server#2]
For each player, the server needs to send a field `clan` which contains the clan Tag.

https://github.com/FAForever/faf-java-server/blob/33dc4cd077a5e77755af3f77a9da5d810391c477/src/main/java/com/faforever/server/integration/legacy/transformer/UserDetailsResponseTransformer.java#L42-L42

**Comment by Geosearchef** [comment]
@IDragonfire Are you still on this?
