### ISSUE TITLE
Increase map play count

### ISSUE THREAD

**Issue by micheljung** [FAForever/faf-java-server#30]
Whenever a game ends, update `table_map_features`.`times_played` of the played map

**Comment by NiklasKopp** [comment]
I'd like to take a shot at this one. Might need some time to find my way in the project, though.

As far as I see it, the place to go here is the onGameEnded(...) method in the GameService?
And I didn't find an entity for the table_map_features table, so in case I didn't overlook something I would create an Entity for this and add it to the MapVersion class?
